;programa que realiza un semáforo 

INITIALIZEVIDEO MACRO VIDEOMODE; MACRO INICIALIZA VIDEO SEGUN VIDEOMODE Y EN GENERAL 00H
    MOV AH, 0
    MOV AL, VIDEOMODE
    INT 10H
ENDM

MOVECURSORTO MACRO COLUMN, ROW
    MOV AH, 2
    MOV DH, ROW 
    MOV DL, COLUMN
    MOV BH, 0
    INT 10H
ENDM

DRAWPIXEL MACRO COLOR
    MOV AH, 09H
    MOV AL, 147 ;ASCII pixel
    MOV BH, 0
    MOV CX, 1
    MOV BL, COLOR
    INT 10H
ENDM

DRAWARROW MACRO COLOR
    MOV AH, 09H
    MOV AL, 60 ;ASCII arrow
    MOV BH, 0
    MOV CX, 1
    MOV BL, COLOR
    INT 10H
ENDM
                         
                         
PAUSESYSTEM MACRO HALFSECONDS
    LOCAL ONESECONDWAIT
    MOV BX, HALFSECONDS
    ONESECONDWAIT:
        DEC BX
        MOV CX, 4ch;08H
        MOV DX, 4b40h ;4240H; espera UN SEGUNDO
        MOV AH, 86H
        INT 15H
        CMP BX, 0
        JNZ ONESECONDWAIT
ENDM    




ORG 100H

INITIALIZEVIDEO 0H

DRAWTRAFFICLIGHTS:
MOVECURSORTO 0, 3 ;0=row, 3=column 
DRAWPIXEL 0000B ;0000B es el color 

MOVECURSORTO 0, 0
DRAWPIXEL 0010B

PAUSESYSTEM 2 ;120 #=halfseconds
;---------------------------------------------
MOVECURSORTO 0, 1
DRAWARROW 0010B

PAUSESYSTEM 2 ;120
;----------------------------------------------
MOVECURSORTO 0, 0
DRAWPIXEL 0000B

MOVECURSORTO 0, 1
DRAWPIXEL 0000B

CALL FLASHYELLOWLIGHT

MOVECURSORTO 0, 2
DRAWPIXEL 0000B

MOVECURSORTO 0, 3
DRAWPIXEL 0100B

PAUSESYSTEM 2 ;120

JMP DRAWTRAFFICLIGHTS

RET

FLASHYELLOWLIGHT PROC
    MOV [0A00H], 6
    FLASH:
        DEC [0A00H]
        MOVECURSORTO 0, 2
        DRAWPIXEL 1110B
        CMP [0A00H], 0
        JZ FINISHFLASHING
        PAUSESYSTEM 1
        DRAWPIXEL 0000B
        CMP [0A00H], 0
        JNZ FLASH
    FINISHFLASHING:
    RET    
FLASHYELLOWLIGHT ENDP
